# Generated by Django 3.0.9 on 2023-03-11 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregistrationmodel',
            options={'permissions': [('create_project', 'Create new project')]},
        ),
    ]
