# Generated by Django 3.0.9 on 2023-03-11 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20230311_1202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Radio_channel',
            new_name='RadioChannel',
        ),
        migrations.RenameModel(
            old_name='Tv_channel',
            new_name='TvChannel',
        ),
    ]
