# Generated by Django 3.0.9 on 2023-04-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20230311_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[('ARTIST', 'Artist'), ('CLIENT', 'Client'), ('TVCHANNEL', 'TvChannel'), ('RADIOCHANNEL', 'RadioChannel')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='usertype',
            field=models.ManyToManyField(to='authapp.UserType'),
        ),
    ]
