# Generated by Django 3.0.9 on 2023-04-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20230414_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[('Artist', 'Artist'), ('Client', 'Client'), ('TvChannel', 'TvChannel'), ('RadioChannel', 'RadioChannel')], primary_key=True, serialize=False),
        ),
    ]
