# Generated by Django 3.0.9 on 2023-04-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20230414_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[('Artist', 'Artists'), ('Client', 'Clients'), ('TvChannel', 'TvChannel'), ('RadioChannel', 'RadioChannel')], primary_key=True, serialize=False),
        ),
    ]
