# Generated by Django 3.0.9 on 2023-05-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20230414_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='usertype',
        ),
        migrations.AlterField(
            model_name='usertype',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[('Artists', 'Artists'), ('Clients', 'Clients'), ('TV Channel', 'TVChannel'), ('Radio Channel', 'RadioChannel')], primary_key=True, serialize=False),
        ),
    ]
