# Generated by Django 3.1.1 on 2023-05-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20230525_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Artists'), (1, 'Clients'), (3, 'TVChannel'), (4, 'RadioChannel')], primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='UserSelection',
        ),
    ]
